import AppKit

/// Something the lazy cat is holding: a copied snippet or image, or a file
/// dropped on it.
enum Clip {
    case text(String)
    case image(NSImage)
    case file(URL)

    /// One line for the menu.
    var title: String {
        switch self {
        case .text(let string):
            let line = string.trimmingCharacters(in: .whitespacesAndNewlines)
                .components(separatedBy: .newlines).first ?? ""
            return line.count > 40 ? String(line.prefix(40)) + "…" : line
        case .image(let image):
            return "Image, \(Int(image.size.width))×\(Int(image.size.height))"
        case .file(let url):
            return url.lastPathComponent
        }
    }

    var thumbnail: NSImage? {
        let source: NSImage
        switch self {
        case .text: return nil
        case .image(let image): source = image
        case .file(let url): source = NSWorkspace.shared.icon(forFile: url.path)
        }
        let size = NSSize(width: 16, height: 16)
        return NSImage(size: size, flipped: false) { rect in
            source.draw(in: rect)
            return true
        }
    }

    func write(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        switch self {
        case .text(let string): pasteboard.setString(string, forType: .string)
        case .image(let image): pasteboard.writeObjects([image])
        case .file(let url): pasteboard.writeObjects([url as NSURL])
        }
    }
}

/// The lazy cat "swallows" whatever you copy and keeps the last few, in
/// memory only. Copies that password managers and other apps mark as
/// secret or temporary are skipped (the nspasteboard.org markers).
final class ClipboardHolder {
    var isEnabled = false {
        didSet {
            guard isEnabled != oldValue else { return }
            isEnabled ? start() : stop()
        }
    }
    /// Called after something new is swallowed.
    var onSwallow: (() -> Void)?
    /// Newest first.
    private(set) var items: [Clip] = []

    private static let limit = 5
    private static let secretTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChange = 0

    /// Files dropped on the cat.
    func add(files: [URL]) {
        files.forEach { remember(.file($0)) }
    }

    /// Puts an item back on the clipboard, ready to paste.
    func restore(at index: Int) {
        guard items.indices.contains(index) else { return }
        items[index].write(to: pasteboard)
        lastChange = pasteboard.changeCount  // ours, don't swallow it again
    }

    func clear() {
        items.removeAll()
    }

    private func start() {
        // Only what's copied from now on, not what was already there.
        lastChange = pasteboard.changeCount
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.check() }
        t.tolerance = 0.2
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    private func stop() {
        timer?.invalidate()
        timer = nil
        items.removeAll()
    }

    private func check() {
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        let types = pasteboard.types ?? []
        guard !types.contains(where: { Self.secretTypes.contains($0) }) else { return }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            urls.forEach { remember(.file($0)) }
        } else if let string = pasteboard.string(forType: .string),
                  !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            remember(.text(string))
        } else if let image = NSImage(pasteboard: pasteboard) {
            remember(.image(image))
        } else {
            return
        }
        onSwallow?()
    }

    private func remember(_ clip: Clip) {
        // Copying the same text again moves it to the top instead of
        // filling the list with duplicates.
        if case .text(let new) = clip {
            items.removeAll { if case .text(let old) = $0 { return old == new } else { return false } }
        }
        if case .file(let new) = clip {
            items.removeAll { if case .file(let old) = $0 { return old == new } else { return false } }
        }
        items.insert(clip, at: 0)
        if items.count > Self.limit { items.removeLast(items.count - Self.limit) }
    }
}
